// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type User struct {
	ID        int64        `json:"id"`
	Nickname  string       `json:"nickname"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}
